#!/bin/bash

cd CImplementation/

if  [[ $1 == "-c" ]]; then
    gcc *.c -o exe -lm && echo "[ OK ] Compliation complete"
elif [[ $1 == "-r" ]]; then
    ./exe
elif [[ $1 == "-cr" ]]; then
    gcc *.c -o exe -lm && echo "[ OK ] Compliation complete" && ./exe
else
    echo -e "Improper arguments supplied..."
    echo -e "Possible arguments:"
    echo -e "\tc - compile the program"
    echo -e "\tr - run the program"
    echo -e "\tcr - first compile, then run the program (assumming no complication errors)"
fi
