#+TITLE:The Queue Oriented Calculator (QO Calc) Official Manual
#+AUTHOR:Brandon Weathers
#+DATE:05/25/2026
#+OPTIONS: toc:nil num:nil
#+LATEX_CLASS_OPTIONS: [12pt]
* Introduction
This is a calculator based on the queue data structure.
There is a master queue, which your cursor in on by default, and a sub-queue, used for auxiliary calculations.
By default you enter numbers into a given queue and then press a operation to act over that function.
Because of the queue's nature, arguments will be dealt with in the order they where entered.
Examples of this will be shown in the following section.
In the function heading the title of each sub-heading is the title of the operation followed by its keybind in parenthesis. 
When referring to a single arbitrary queue its elements will be named from x_1 to x_n.
When referring specifically to the master and sub-queues, they will be named a_1 to a_n and b_1 to b_n accordingly.
* Arithmetic
** Addition (+)
$$
x_1 := (...((x_1 + x_2) + x_3) + ... + x_n)
$$
** Subtraction (-)
$$
x_1 := (...((x_1 - x_2) - x_3) - ... - x_n)
$$
** Multiplication (*)
$$
x_1 := (...((x_1 * x_2) * x_3) * ... * x_n)
$$
** Division (/)
$$
x_1 := \frac{\frac{\frac{x_1}{x_2}}{x_3}}{...x_n}
$$
** Exponentiation
*** Left-to-right exponentiation (^)
$$
x_1 := ((x_1^{x_2})^{x_3})^{...x_n}
$$
*** Right-to-left exponentiation (c-^)
$$
x_1 := x_1^{x_2^{x_3^{...x_n}}}
$$
** Logarithms (L)
$$
x_1 := \log..._{\log_{\log_{x_1}(x_2)}(x_3)}(x_n)
$$
* General
** Move Cursor Right (l)
Moves the cursor to the right to select the rightmost queue.
** Move Cursor Left (h)
Moves the cursor to the left to select the leftmost  queue.
** Clear Selected Queue (c)
Removes all elements from the selected queues.
** Agreegate All Queues to the Right (H)
No matter which queue the cursor is on, all elements get appended to the end of the master queue.
$$
x_1 := x_1
$$
$$
x_2 := x_2
$$
$$
x_3 := x_3
$$
$$
...
$$
$$
x_{2-n} := y_{2-m}
$$
$$
x_{1-n} := y_{1-m}
$$
$$
x_{n} := y_{m}
$$
* Roots
** Square Root (q)
For each element in the array
$$
x_1 := \sqrt{x_1}
$$
$$
x_2 := \sqrt{x_2}
$$
$$
x_3 := \sqrt{x_3}
$$
$$
...
$$
$$
x_n := \sqrt{x_n}
$$
* Statistics
** Maximum (M)
x_1 := MIN {x_1, x_2, x_3, ... x_n}
** Minimum (m)
x_1 := MAX {x_1, x_2, x_3, ... x_n}
